# Projective transformation

**Projective transformation** is any invertimle matrix transformation for homogeneou s coordinates $\mathbb{P}^2 \rightarrow \mathbb{P}^2 $

Let $A$ be a projective transformation.

It maps $p$ to $p'$: $p' \sim Ap$. 

Note: we use "$ \sim $" insread of "$=$" because $p'$ in homogeneous coordinates is defined up to a scaling factor.

$\lambda p' = Ap$

Projective transformation maps collinear points to collinear points.


## Computing collinear transformation

One has to have at least 
4 non collinear points to compute a projective transformation.

Let's say $M$ maps $a$, $b$, $c$, $d$ to $a'$, $b'$, $c'$, $d'$ respectively:

$a' \sim Ma$, ...  $d' \sim Md$.


In order to compute $M$ first we have to decompose d as a linear combination of a, b, c. It is possible because $a,b,c, d \in \mathbb{R}^3$ and they are not collinear.

$d =  \alpha a + \beta b + \gamma c$

Writing that as a matrix form gives us a linear system that has a single solution:

$
\begin{pmatrix}
a_{3 \times 1} & b_{3 \times 1} & c_{3 \times 1}
\end{pmatrix}_{3 \times 3}
    \cdot
\begin{pmatrix}
\alpha \\ \beta \\ \gamma
\end{pmatrix}
= d
$


$
\begin{pmatrix}
\alpha \\ \beta \\ \gamma
\end{pmatrix}
=
\begin{pmatrix}
a & b & c
\end{pmatrix}^{-1}
\cdot d
$


Note that matrix $K_{abc}=\begin{pmatrix}a & b & c\end{pmatrix}_{3 \times 3}$ maps basis vectors to it's columns:
$\begin{pmatrix}1 \\ 0 \\ 0\end{pmatrix}$ to $a$,
$\begin{pmatrix}0 \\ 1 \\ 0\end{pmatrix}$ to $b$,
$\begin{pmatrix}0 \\ 0 \\ 1\end{pmatrix}$ to $c$.


if we multiply columns of the matrix 
$K_{abc}=\begin{pmatrix}a & b & c\end{pmatrix}$ 
by 
$\alpha, \beta,  \gamma$ 
we get a matrix 

$A = \begin{pmatrix}\alpha a & \beta b & \gamma c\end{pmatrix}$

that maps the same basis vectors to the scaled versions of $a,b,c$.


Doing the same operation with $a', b', c', d'$ we get another matrix


$B = \begin{pmatrix}\alpha' a' & \beta' b' & \gamma' c'\end{pmatrix}$

that maps the basis vectors to $\alpha' a'$, $\beta' b'$ and $\gamma' c'$.

In order to compute a final transformation between $a,b,c,d$ and $a', b', c', d'$ we first go from basis of $a,b,c$ to basis of $(1,0,0)^T, (0,1,0)^T, (0,0,1)^T$ using A^{-1}. Then we go from the basis of $(1,0,0)^T, (0,1,0)^T, (0,0,1)^T$ to the target basis of $a',b',c'$ using $B$.

Final transformation $M = B \cdot A^{-1}$

## Examples


### Example 3 from coursera quiz 
M keeps the points (0,0,1) and (1,1,1)fixed and maps point (1,0,1) to (1,0,0) and point (0,1,1) to (0,1,0)

In [1]:
import numpy as np

computing transformation from standard basis to scaled source vectors...

In [2]:

a = [0,0,1]
b = [1,1,1]
c = [1,0,1]
d = [0,1,1]

# coeffs = [alpha beta gamma]
coeffs = np.linalg.inv(np.array([a,b,c]).T) @ d
coeffs

array([ 1.,  1., -1.])

In [3]:
# scaled matrix
A = np.array([a,b,c]).T * coeffs
A

array([[ 0.,  1., -1.],
       [ 0.,  1., -0.],
       [ 1.,  1., -1.]])

computing transformation from standard basis to scaled target vectors...

In [4]:
a_ = [0,0,1]
b_ = [1,1,1]
c_ = [1,0,0]
d_ = [0,1,0] 

# coeffs_ = [alpha_ beta_ gamma_]
coeffs_ = np.linalg.inv(np.array([a_,b_,c_]).T) @ d_
coeffs_

array([-1.,  1., -1.])

In [5]:
# scaled matrix
B = np.array([a_,b_,c_]).T * coeffs_
B

array([[-0.,  1., -1.],
       [-0.,  1., -0.],
       [-1.,  1., -0.]])

computing the final transformation: 

In [6]:
M = B @ np.linalg.inv(A)
M

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  1., -1.]])

scaled versions of M are also correct:

In [7]:
M * (-1)

array([[-1., -0., -0.],
       [-0., -1., -0.],
       [-1., -1.,  1.]])