In [1]:
import numpy as np

def skew(x):
    return np.array([[0, -x[2], x[1]],
                     [x[2], 0, -x[0]],
                     [-x[1], x[0], 0]])
x = [1,2,3]
y = np.array([1,2,3])

In [2]:
from pytransform3d import rotations as pr


random_state = np.random.RandomState(0)

rot1 = pr.random_quaternion(random_state)


In [3]:
R = pr.matrix_from_quaternion(rot1)

In [4]:
skew(x).T == -skew(x)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
skew(x) @ x 

array([0, 0, 0])

In [19]:
np.array(x).T @ skew(x)

array([0, 0, 0])

In [22]:
R.T @ skew(x) @ R - skew(R.T@x)

array([[ 1.34405231e-17, -1.77635684e-15,  7.77156117e-16],
       [ 1.33226763e-15,  7.61433025e-17, -4.44089210e-16],
       [-8.88178420e-16,  2.22044605e-16,  5.69068517e-18]])

In [8]:
# 2

R.T @ skew(y) @ R,  skew(R.T @ y)

(array([[ 1.34405231e-17, -3.48506344e+00,  8.69934041e-01],
        [ 3.48506344e+00,  7.61433025e-17, -1.04763904e+00],
        [-8.69934041e-01,  1.04763904e+00,  5.69068517e-18]]),
 array([[ 0.        , -3.48506344,  0.86993404],
        [ 3.48506344,  0.        , -1.04763904],
        [-0.86993404,  1.04763904,  0.        ]]))

In [15]:
R[:, 1] @ skew(y) @ R[:, 2]

-1.0476390357156573

In [14]:
skew(y)

array([[ 0, -3,  2],
       [ 3,  0, -1],
       [-2,  1,  0]])

In [29]:
# 3

In [32]:
rot1 = pr.random_quaternion(random_state)
rot2 = pr.random_quaternion(random_state)
R1 = pr.matrix_from_quaternion(rot1)
R2 = pr.matrix_from_quaternion(rot2)
T1 = np.array([1,2,3])
T2 = np.array([3,4,5])
XW = np.array([0.2,0.3,0.12])
X1 = R1.T @ (XW-T1)
X2 = R2.T @ (XW-T2)
X1, X2

(array([-2.76576319,  0.57583861, -1.96044992]),
 array([-2.49865452,  2.62616695, -5.67488967]))

In [37]:
E = R1.T @ skew(T2-T1) @ R2
X1 @ E @ X2, X2 @ E @ X1, 

(5.329070518200751e-15, -20.851118111428242)

In [38]:
E = R1.T @ skew(T1-T2) @ R2
X1 @ E @ X2, X2 @ E @ X1, 

(-5.329070518200751e-15, 20.851118111428242)

In [40]:
E = skew(R1.T @ (T2-T1)) @ (R1.T @ R2)
X1 @ E @ X2, X2 @ E @ X1, 

(5.329070518200751e-15, -20.851118111428235)

In [41]:
E = skew(R1.T @ (T1-T2)) @ (R1.T @ R2)
X1 @ E @ X2, X2 @ E @ X1, 

(-5.329070518200751e-15, 20.851118111428235)

In [23]:
# 9

In [16]:
E = np.array([0, 1, 0, 2**-0.5, 0, -2**-0.5, 0, 1, 0]).reshape(3,3)
print(E)
print(np.linalg.svd(E))

[[ 0.          1.          0.        ]
 [ 0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]]
(array([[-0.70710678,  0.        , -0.70710678],
       [ 0.        , -1.        ,  0.        ],
       [-0.70710678,  0.        ,  0.70710678]]), array([1.41421356, 1.        , 0.        ]), array([[ 0.        , -1.        ,  0.        ],
       [-0.70710678,  0.        ,  0.70710678],
       [-0.70710678,  0.        , -0.70710678]]))


In [17]:
E = np.array([0, 0, 0, 2**-0.5, 0, -2**-0.5, 0, 1, 0]).reshape(3,3)
print(E)
print(np.linalg.svd(E))

[[ 0.          0.          0.        ]
 [ 0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]]
(array([[ 0.,  0., -1.],
       [-1.,  0.,  0.],
       [ 0.,  1.,  0.]]), array([1., 1., 0.]), array([[-0.70710678,  0.        ,  0.70710678],
       [-0.        ,  1.        ,  0.        ],
       [-0.70710678,  0.        , -0.70710678]]))


In [18]:
E = np.diag([2,1,0])
print(E)
print(np.linalg.svd(E))

[[2 0 0]
 [0 1 0]
 [0 0 0]]
(array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), array([2., 1., 0.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [19]:
E = np.diag([1,1,0])
print(E)
print(np.linalg.svd(E))

[[1 0 0]
 [0 1 0]
 [0 0 0]]
(array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]]), array([1., 1., 0.]), array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]]))
